# Generated by Django 3.0.6 on 2020-05-31 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midterm',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.SmallIntegerField(null=True)),
                ('semester', models.SmallIntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.Department')),
            ],
        ),
        migrations.CreateModel(
            name='MidRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Midterm')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Course')),
            ],
        ),
        migrations.CreateModel(
            name='FinalRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Midterm')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Final',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.SmallIntegerField(null=True)),
                ('semester', models.SmallIntegerField(null=True)),
                ('set_date', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.Department')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.SmallIntegerField(null=True)),
                ('semester', models.SmallIntegerField(null=True)),
                ('section', models.CharField(max_length=2, null=True)),
                ('topics', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.Department')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.Course')),
                ('will_take', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.TeacherInfo')),
            ],
        ),
    ]
