# Generated by Django 3.0.6 on 2020-05-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='midterm',
            name='set_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='final',
            name='set_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
