# Generated by Django 3.0.6 on 2020-06-09 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='linkedin_url',
        ),
        migrations.AddField(
            model_name='phonebook',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='_account_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='_account_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='course_takes',
            field=models.ManyToManyField(default=None, related_name='course_takes', to='department.Course'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=9, null=True)),
                ('joining_date', models.DateField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('administrator_type', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Editor', 'Editor')], max_length=11)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='department.Department')),
            ],
        ),
    ]
