# Generated by Django 3.0.6 on 2020-06-03 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('accounts', '0002_auto_20200602_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='linkedin_url',
        ),
        migrations.AddField(
            model_name='phonebook',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='course_takes',
            field=models.ManyToManyField(default=None, related_name='course_takes', to='department.Course'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
