# Generated by Django 3.0.6 on 2020-06-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200603_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
